services:
  keycloak:
    image: keycloak/keycloak:26.0
    volumes:
      - ./build/libs/:/opt/keycloak/providers/
      - ./demo/:/opt/keycloak/data/import/
    ports:
      - "80:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --import-realm